general {
    lock_cmd = pidof hyprlock || hyprlock       # команда блокировки
    before_sleep_cmd = loginctl lock-session    # блокировка перед сном
    after_sleep_cmd = hyprctl dispatch dpms on  # включить экран после сна
}

listener {
    timeout = 900                                # 15 минут в секундах
    on-timeout = hyprctl dispatch dpms off       # выключить экран
    on-resume = hyprctl dispatch dpms on         # включить экран при активности
}


